apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-test-app
  template:
    metadata:
      labels:
        app: kargo-test-app
    spec:
      containers:
        - name: kargo-test-app
          image: ghcr.io/yhrn/kargo-test-app:placeholder
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
