apiVersion: v1
kind: Service
metadata:
  name: kargo-test-app
spec:
  type: NodePort
  selector:
    app: kargo-test-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
    nodePort: placeholder
