apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30093
  target:
    kind: Service
    name: kargo-test-app
images:
- name: ghcr.io/yhrn/kargo-test-app
  newTag: 7580513ae708505dbfd2d069d7b07b0bc7a64b3c
