apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-test
  namespace: kargo-test
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/yhrn/kargo-test-app
      imageSelectionStrategy: NewestBuild
      gitRepoURL: https://github.com/yhrn/kargo-test.git
